version: "3.6"
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo_data:/data/db
    command: mongod --smallfiles
    networks:
      - default
      - traefik-public
  rocketchat:
    image: rocket.chat:latest
    networks:
      - default
      - traefik-public
    links:
      - mongo
    environment:
      - ROOT_URL=${SCHEMA:-https}://${DOMAIN?Variable DOMAIN not set}
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    depends_on:
      - mongo
    deploy:
      labels:
        - traefik.frontend.rule=Host:${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
volumes:
  mongo_data:
networks:
  traefik-public:
    external: true
