version: "3.6"
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo_data:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs01
    networks:
      - default
      - traefik-public

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs01'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    networks:
      - default
      - traefik-public
    depends_on:
      - mongo

  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    links:
      - mongo
    environment:
      - ROOT_URL=${DOMAIN?Variable DOMAIN not set}
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs01
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs01
    depends_on:
      - mongo
    deploy:
      labels:
        - traefik.frontend.rule=Host:${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
rocket:
  image: rocket.chat
  networks:
    - default
    - traefik-public
  links:
  deploy:
    labels:
      - traefik.frontend.rule=Host:${DOMAIN?Variable DOMAIN not set}
      - traefik.enable=true
      - traefik.port=8080
      - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
      - traefik.docker.network=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https
volumes:
  mongo_data:
networks:
  traefik-public:
    external: true
